import turtle
import random

turtle.title("Random Triangles")

color_to_use = turtle.textinput("Fill Color", "What color should the triangles be filled with? ")

starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
starting_x = random.randint(-200, 200)
starting_y = random.randint(-200, 200)
t_size = random.randint(50, 200)
turtle.penup()
turtle.goto(starting_x, starting_y)
turtle.setheading(0)
turtle.pendown()

if color_to_use == "green":
    color_to_use = random.choice(['red', 'yellow', 'pink', 'orange', 'purple', 'blue'])
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
else:
    turtle.fillcolor(color_to_use)
    turtle.begin_fill()
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.left(120)
    turtle.forward(t_size)
    turtle.end_fill()
    
turtle.hideturtle()
turtle.done()